[package]
name = "hf"
version = "0.1.0"
authors = ["Sam Delmerico <svdelmerico@gmail.com>"]

[dependencies]
regex = "*"
rand = "*"
nalgebra = "0.16.0"

[dependencies.lapack]
version = "0.11"
default-features = false
features = [ "netlib" ]
